// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znrrmpbjeunqcznxitmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpucnJtcGJqZXVucWN6bnhpdG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDM5MzksImV4cCI6MjA2NTg3OTkzOX0.JJJpZ1kfF9dXPLSvZaZ409Os4L_t3tTjj3NlfreMhB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);